name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        platform: [windows-2019]
        include:
        - platform: windows-2019
          vcpkgCommitId: '388e9f1c82e077d4cea8f94991c6e31599f1239b'
    runs-on: ${{ matrix.platform }}
    env:
      CMAKE_PRESET: windows-release
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
      - name: Run CMake
        uses: lukka/run-cmake@v10.5
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: '${{ env.CMAKE_PRESET }}'
          buildPreset: '${{ env.CMAKE_PRESET }}'